const seniors = [
	'Vandan Ayyalapu (Tuba)',
	'Ananta Bajpai (Front Ensemble)',
	'Jon Cattafesta (Baritone)',
	'Jenny Chen (Clarinet)',
	'Mercedes Chin (Drum Major)',
	'Anisha Dadhich (Front Ensemble)',
	'Bea Elliott (Head Drum Major)',
	'Alisia Gomolka (Colorguard)',
	'Anisha Javaji (Flute)',
	'Abby Kamon (Baritone)',
	'Jason Keffer (Baritone)',
	'Aparna Kumar (Flute)',
	'Mackenzie Lee (Battery)',
	'Shritej Mamidala (Clarinet)',
	'Suhasini Mummidi (Trumpet)',
	'Sean Owellen (Clarinet)',
	'Anthony Pham (Clarinet)',
	'Adithi Pillai (Colorguard)',
	'Tanush Prattipati (Mellophone)',
	'Melanie Ryan (Front Ensemble)',
	'Ava Schwinn (Colorguard)',
	'Atharv Singh (Battery)',
	'Odin Sterling (Baritone)',
	'Tal Sterling (Trumpet)',
	'Olivia Talton (Battery)',
	'Diane Vijay (Flute)',
	'Ryan Wang (Clarinet)',
	'Evan Washington (Tuba)',
	'Kaitlyn Wilhelm (Tuba)',
	'Darren Zhang (Baritone)'
];

export { seniors };
